Repository ModestosV/Simple-Calculator-DreamTeam, pull requests merged in 2018-02, with the labels that each got.

#41 Clear button functionality changed.
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
Labels: Bug Fix

#39 Marcdragon123/storage
  app/build.gradle
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Config.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MyWidgetProvider.kt
  app/src/main/res/mockito-extensions/org.mockito.plugins.MockMaker
  app/src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt
  app/src/test/resources/data.json
Labels: Needs Review, Testing needed

#43 Arkondoma/equation tests
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/javaluator/AbstractEvaluator.java
  app/src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt
Labels: Bug Fix, Needs Review, Ongoing

#44 Updated clear button functionality.
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/res/layout/activity_main.xml
Labels: git tag release1

#47 Modestos v/remove unused code
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/WidgetConfigureActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MyWidgetProvider.kt
  app/src/main/res/xml/widget_info.xml
  app/src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt
Labels: Dev

#49 Modestos v/calculator modes
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/res/layout/activity_main.xml
Labels: Enhancement, Testing needed, UI
