Repository ModestosV/Simple-Calculator-DreamTeam, pull requests merged in 2018-03, with the labels that each got.

#53 George/paste number
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
Labels: Approved, Completed, Needs Review, Ongoing

#52 Marcdragon123/storage
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/HistoryActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/FileHandler.java
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/values.xml
  app/src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt
  build.gradle
Labels: Approved, Completed, Enhancement, help wanted

#61 Noah/changetextbuttons
  app/src/androidTest/java/com/simplemobiletools/calculator/MainActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt
Labels: Bug Fix, Completed, Enhancement, UI

#67 Mikebasdeo/updatedunitconversion
  app/src/androidTest/java/com/simplemobiletools/calculator/UnitConversionTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/HistoryActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/UnitConversionActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/Converter.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/LengthConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/SpeedConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/TemperatureConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/TimeConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/VolumeConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/conversions/WeightConversion.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/Constants.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/FileHandler.java
  app/src/main/kotlin/com/simplemobiletools/calculator/javaluator/AbstractEvaluator.java
  app/src/main/res/layout/activity_unit_conversion.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/layout/spinner_item_units.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/values.xml
Labels: Bug Fix, Completed, Enhancement, UI, git tag release2
